backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
publish_mode: editorial_workflow
media_folder: "/static/" # Media files will be stored in the repo under images/uploads
public_folder: "/static/" # The src attribute for uploaded media will begin with /images/uploads
collections:
  - name: "project" # Used in routes, e.g., /admin/collections/blog
    label: "Project" # Used in the UI
    folder: "projects" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Hero Image", name: "hero_image", widget: "image"}
      - {label: "Thumbnail Image", name: "thumb_image", widget: "image"}
      - {label: "thumb columns", name: "col", widget: "number"}
      - {label: "thumb rows", name: "row", widget: "number"}
      - {label: "hero color", name: "hero_color", widget: "color"}
      - {label: "Body", name: "body", widget: "markdown"}
      - {label: "Exceprt", name: "excerpt", widget: "markdown"}